spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

# Spring Data REST properties

# spring:
#   data:
#     rest:
#       base-path: /magic-api
#       default-page-size: 3
